spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: Pratham@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080

